# Generated by Django 2.2.4 on 2019-08-23 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('texto_comentario', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('valor', models.FloatField()),
                ('imagem', models.ImageField(upload_to='produtos')),
                ('descricao', models.CharField(max_length=500)),
                ('quantidade', models.PositiveIntegerField()),
                ('comentario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appproduto.Comentario')),
            ],
        ),
    ]
