# Generated by Django 2.2.4 on 2019-08-16 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appproduto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('texto_comentario', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='produto',
            name='comentario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appproduto.Comentario'),
            preserve_default=False,
        ),
    ]
