# Generated by Django 2.2.4 on 2019-08-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appproduto', '0003_auto_20190816_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='quantidade',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
