# Generated by Django 2.2.4 on 2019-08-16 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appproduto', '0004_produto_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='comentario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appproduto.Comentario'),
        ),
    ]
