# Generated by Django 2.2.4 on 2019-08-18 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appproduto', '0005_auto_20190816_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='quantidade',
            field=models.PositiveIntegerField(),
        ),
    ]
