# Generated by Django 2.2.4 on 2019-08-19 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appproduto', '0006_auto_20190818_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscal',
            name='codigo',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
