# Generated by Django 2.2.4 on 2019-08-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appproduto', '0010_auto_20190819_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(height_field=100, upload_to='produtos', width_field=100),
        ),
    ]
