# Generated by Django 2.2.4 on 2019-08-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appproduto', '0013_auto_20190820_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='quantidade_pedido',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
