# Generated by Django 2.2.4 on 2019-08-20 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appproduto', '0014_pedido_quantidade_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='quantidade_pedido',
        ),
    ]
