# Generated by Django 2.2.4 on 2019-08-21 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appusuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complementouser',
            name='pedido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedido_from_user', to='appproduto.Pedido'),
        ),
    ]
